"""
Django settings for store_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import sys
sys.path.insert(0, os.path.join(BASE_DIR, 'db_backends'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4h0)2!kw(+0(8h^1y*e96*7v)802qor_#n$@ilznmlga%zlq2i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','192.168.100.36']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounting.middleware.LoginRequiredMiddleware',  # اضافه کردن middleware لاگین
]

ROOT_URLCONF = 'store_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'store_project.wsgi.application'


# Database
# store_project/settings.py
# store_project/settings.py

# در بالای فایل settings.py این خط را اضافه کنید تا مسیر پروژه به پایتون شناسانده شود

import sys
sys.path.insert(0, os.path.join(BASE_DIR, 'db_backends'))

# settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'legacy': {
        # مسیر کامل به فایل base.py سفارشی خودمان را می‌دهیم
        'ENGINE': 'mssql_custom',  # <--- تغییر کلیدی
        'NAME': 'MahakDB',
        'USER': 'sa',
        'PASSWORD': 'Lavan581@',
        'HOST': 'localhost',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;Encrypt=no',
        },
    }
}
DATABASE_ROUTERS = ['store_project.db_router.LegacyRouter']

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ========================================
# تنظیمات احراز هویت
# ========================================

# آدرس صفحه لاگین سفارشی
LOGIN_URL = 'login'

# آدرس هدایت بعد از لاگین موفق
LOGIN_REDIRECT_URL = 'home'

# آدرس هدایت بعد از لاگ‌اوت
LOGOUT_REDIRECT_URL = 'home'

# تنظیمات Session
SESSION_COOKIE_AGE = 3600  # 1 ساعت
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# تنظیمات Messages
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ========================================
# تنظیمات بکند احراز هویت سفارشی
# ========================================

# استفاده از بکند سفارشی برای احراز هویت
AUTHENTICATION_BACKENDS = [
    'accounting.authentication.LegacyDBBackend',
    # 'django.contrib.auth.backends.ModelBackend',  # این خط را کامنت کرده‌ایم
]

# ========================================
# تنظیمات مدل کاربر سفارشی
# ========================================

# به جنگو می‌گوییم مدل کاربر پیش‌فرض ما این است
AUTH_USER_MODEL = 'accounting.LegacyUser'
